#!/bin/bash

RIAK_NODE_HOST=$(hostname -i)
RIAK_DATA_DIR=/var/lib/riak/$RIAK_NODE_NAME
RIAK_LOG_DIR=$RIAK_DATA_DIR/log

if [ $KUBERNETES_SERVICE_PORT -eq 443 ]; then
  KUBE_MASTER_ENDPOINT="https://$KUBERNETES_SERVICE_HOST"
elif [ $KUBERNETES_SERVICE_PORT -eq 6443 ]; then
  KUBE_MASTER_ENDPOINT="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
else
  KUBE_MASTER_ENDPOINT="http://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
fi

# Sibling discovery: get the IP of any running riak pod
#RIAK_ROLE="riak-kv"
#RIAK_CLUSTER_JOIN=$(curl --insecure --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" "${KUBE_MASTER_ENDPOINT}/api/v1/namespaces/${KUBE_NAMESPACE}/pods/?pretty=false" | jq -r ".items | map(select(.metadata.labels[\"role\"] == \"${RIAK_ROLE}\")) | map(select(.status.phase == \"Running\")) | map(.metadata.name + \"@\" + .status.podIP) | map(select(. != \"${RIAK_NODE_NAME}\")) | .[0]")
#if [ "$RIAK_CLUSTER_JOIN" == "null" ]; then
#  RIAK_CLUSTER_JOIN=""
#fi

# We have to also make /var/log/riak since erlang.log's location seems tb be unconfigurable
mkdir -p $RIAK_DATA_DIR $RIAK_LOG_DIR /var/log/riak
chown -R riak:riak /var/lib/riak $RIAK_DATA_DIR $RIAK_LOG_DIR /var/log/riak

m4 \
  -DRIAK_NODE_HOST=$RIAK_NODE_HOST \
  -DRIAK_NODE_NAME=$RIAK_NODE_NAME \
  -DRIAK_DATA_DIR=$RIAK_DATA_DIR \
  -DRIAK_LOG_DIR=$RIAK_LOG_DIR \
  riak.conf.m4 > /etc/riak/riak.conf

chown riak:riak $RIAK_DATA_DIR $RIAK_LOG_DIR
chmod 0755 $RIAK_DATA_DIR $RIAK_LOG_DIR

riak start
setuser riak riak ping
if [ "$RIAK_CLUSTER_JOIN" = "$RIAK_NODE_NAME" ]; then
  echo "We are the cluster leader."
else
  riak-admin cluster status | grep "$RIAK_CLUSTER_JOIN"
  if [ $? -eq 0 ]; then
    echo "Already a member of the cluster at $RIAK_CLUSTER_JOIN"
  else
    echo "Joining the cluster at $RIAK_CLUSTER_JOIN"
    riak-admin cluster join $RIAK_CLUSTER_JOIN
    if [ $? -ne 0 ]; then
      echo "Failed to join cluster! Aborting."
      exit 1
    fi
  fi
  riak-admin cluster status
  # If the last to join, (re)commit the cluster.
  if riak-admin member-status | egrep "joining|valid" | wc -l | grep -q "$RIAK_CLUSTER_SIZE"; then
      riak-admin cluster plan && riak-admin cluster commit
  fi
fi

function stop_riak {
  riak stop
}

trap stop_riak EXIT

sleep infinity
