#!/bin/bash

RIAK_NODE_HOST=$(hostname -i)
#RIAK_NODE_NAME=$(hostname)@$RIAK_NODE_HOST
RIAK_DATA_DIR=/var/lib/riak/$RIAK_NODE_NAME
RIAK_LOG_DIR=/var/log/riak

if [ $KUBERNETES_SERVICE_PORT -eq 443 ]; then
  KUBE_MASTER_ENDPOINT="https://$KUBERNETES_SERVICE_HOST"
elif [ $KUBERNETES_SERVICE_PORT -eq 6443 ]; then
  KUBE_MASTER_ENDPOINT="https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
else
  KUBE_MASTER_ENDPOINT="http://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT"
fi

# Get the IP of any running riak sibling
RIAK_ROLE="riak-kv"
RIAK_CLUSTER_LEADER=$(curl --insecure --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" "${KUBE_MASTER_ENDPOINT}/api/v1/namespaces/${KUBE_NAMESPACE}/pods/?pretty=false" | jq -r ".items | map(select(.metadata.labels[\"role\"] == \"${RIAK_ROLE}\")) | map(select(.status.phase == \"Running\")) | map(.metadata.name + \"@\" + .status.podIP) | map(select(. != \"${RIAK_NODE_NAME}\")) | .[0]")
if [ "$RIAK_CLUSTER_LEADER" == "null" ]; then
  RIAK_CLUSTER_LEADER=""
fi

m4 \
  -DRIAK_NODE_HOST=$RIAK_NODE_HOST \
  -DRIAK_NODE_NAME=$RIAK_NODE_NAME \
  -DRIAK_DATA_DIR=$RIAK_DATA_DIR \
  -DRIAK_LOG_DIR=$RIAK_LOG_DIR \
  riak.conf.m4 > /etc/riak/riak.conf

chown riak:riak $RIAK_DATA_DIR $RIAK_LOG_DIR
chmod 0755 $RIAK_DATA_DIR $RIAK_LOG_DIR

riak start
riak ping
if [ -z "$RIAK_CLUSTER_LEADER" ]; then
  echo "We are the cluster leader."
else
  echo "Joining the cluster at $RIAK_CLUSTER_LEADER"
  riak-admin cluster join $RIAK_CLUSTER_LEADER
  riak-admin cluster status
  # If the last to join, (re)commit the cluster.
  if riak-admin member-status | egrep "joining|valid" | wc -l | grep -q "$RIAK_CLUSTER_SIZE"; then
      riak-admin cluster plan && riak-admin cluster commit
  fi
fi

# Sleep while riak is alive
while [ true ]; do
  sleep 30
  riak ping
  if [ $? -ne 0 ]; then
    sleep 1
    echo "Retrying ping..."
    riak ping
    if [ $? -ne 0 ]; then
      sleep 5
      echo "Retrying ping again..."
      riak ping
      if [ $? -ne 0 ]; then
        echo "Exiting"
        exit 1
      fi
    fi
  fi
done
