options:
  repository: arctype # Docker repository
  cluster: local
  environment: default

clusters:
  local:
    provider: native
    kubeconfig: .kubeconfig

environments: 
  default: 
    services: {}
