#!/bin/sh

MYID=${HOSTNAME##*-}
ZOODATA=${ZOODATA}/${MYID}

logger "Starting Zookeeper $MYID"

mkdir -p ${ZOODATA}
echo $MYID > ${ZOODATA}/myid

# server.1=...
if [ -n "$SERVERS" ]; then
  python -c "print '\n'.join(['server.%i=%s:2888:3888' % (i + 1, x) for i, x in enumerate('$SERVERS'.split(','))])" > ${ZOOCFGDIR}/servers.cfg
else
  echo > ${ZOOCFGDIR}/servers.cfg
fi

# Includes servers.cfg
m4 -I $ZOOCFGDIR \
  -DZOODATA=$ZOODATA \
  $ZOOCFG_M4 \
  > ${ZOOCFGDIR}/zoo.cfg

# Put log4j.properties in the right place
cp -f $LOG4J_PROPERTIES_PATH ${ZOOCFGDIR}/log4j.properties

chown -R zookeeper:zookeeper $ZOODATA

setuser zookeeper /opt/zookeeper/bin/zkServer.sh start-foreground
