#!/bin/sh

mkdir /var/log/caddy
m4 \
  -D S3_ACCESS_KEY="$S3_ACCESS_KEY" \
  -D S3_SECRET_KEY="$S3_SECRET_KEY" \
  -D S3_TARGET="$S3_TARGET" \
  /etc/service/collector/crontab.m4 > /etc/service/collector/crontab
crontab -u root /etc/service/collector/crontab
