#!/bin/bash

cd ${SECOR_INSTALL_DIR}
exec java -ea -Dsecor_group=${SECOR_GROUP:-secor_backup} \
  -Dlog4j.configuration=${LOG4J_PROPERTIES:-log4j.prod.properties} \
  -Dconfig=${SECOR_PROPERTIES:-secor.prod.backup.properties} \
  -cp secor.jar:lib/* \
  com.pinterest.secor.main.ConsumerMain
