#!/bin/bash

cd ${SECOR_INSTALL_DIR}
exec java -ea \
  -Dlog4j.configuration=${LOG4J_PROPERTIES:-file:/etc/service/secor/log4j.properties} \
  -Dconfig=${SECOR_PROPERTIES:-secor.prod.backup.properties} \
  -cp secor.jar:lib/* \
  com.pinterest.secor.main.ConsumerMain
