#!/bin/bash

exec prometheus \
  --config.file="${PROMETHEUS_CONFIG:-/usr/go/src/github.com/prometheus/prometheus/documentation/examples/prometheus.yml}" \
  --web.external-url="${PROMETHEUS_URL:-http://localhost:9090}"
