#!/bin/bash

set -e

cd /var/www/orocommerce

if [ ! -f "config/config.yml" ]; then
  cp -rf /etc/service/orocommerce/default-config/* config/
fi

chown -R www-data:www-data cache config
if [ ! -f /var/run/orocommerce-init ]; then
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console fos:js-routing:dump --env=prod
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console oro:localization:dump --env=prod
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console assets:install --env=prod
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console assetic:dump --env=prod
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console oro:translation:dump --env=prod
  setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console oro:requirejs:build --env=prod
  logger "OroCommerce initialization complete"
  touch /var/run/orocommerce-init
fi
echo "Starting OroCommerce message queue consumer"
setuser www-data /usr/bin/php7.1 -c /etc/service/php-fpm/php.ini /var/www/orocommerce/bin/console oro:message-queue:consume --env=prod > /dev/null
