#!/bin/bash

set -e

ORO_ENV=${ORO_ENV:-prod}

# Installs orocommerce only if it does not already exist.
if [ ! -f /var/www/orocommerce/README.md ]; then
  echo "Installing /var/www/orocommerce";
  cp -rf /usr/lib/orocommerce /var/www/
  chown -R www-data:www-data /var/www/orocommerce
  echo '`sv restart orocommerce` when installation is complete.'
  sleep infinity
fi

cd /var/www/orocommerce

echo "Rebuilding assets"
setuser www-data /usr/bin/php  ./bin/console oro:assets:install --env=$ORO_ENV > /dev/null

echo "Starting OroCommerce message queue consumer"
exec setuser www-data /usr/bin/php ./bin/console oro:message-queue:consume --env=$ORO_ENV > /dev/null
