#!/bin/bash

set -e

ORO_ENV=${ORO_ENV:-prod}

if [ ! -f /var/www/orocommerce/README.md ]; then
  sleep infinity
fi

cd /var/www/orocommerce

echo "Starting OroCommerce web socket server"
exec setuser www-data /usr/bin/php ./bin/console gos:websocket:server --env=$ORO_ENV > /dev/null
