#!/bin/bash

set -e

ORO_ENV=${ORO_ENV:-prod}

while [ ! -f /var/www/orocommerce/README.md ]; do
  echo "Waiting for /var/www/orocommerce"
  sleep 5
done

cd /var/www/orocommerce

echo "Starting OroCommerce web socket server"
exec setuser www-data /usr/bin/php ./bin/console gos:websocket:server --env=$ORO_ENV > /dev/null
