#!/bin/bash

tar -C /etc/openvpn -xzf /etc/service/openvpn/secret/openvpn.tgz

iptables -t nat -A POSTROUTING -s $VPN_VIRTUAL_NAT -o eth0 -j MASQUERADE
openvpn --config ${OPENVPN_CONF_PATH} --dev tun
