#!/bin/bash

function start_kafka {
  logger "Starting Kafka broker $BROKER_ID"
  setuser kafka /usr/local/kafka/bin/kafka-server-start.sh /etc/service/kafka/server.properties
}

function stop_kafka {
  setuser kafka /usr/local/kafka/bin/kafka-server-stop.sh
}

BROKER_ID=${HOSTNAME##*-}
KAFKA_LOG_DIRS=${KAFKA_LOG_DIRS}/${BROKER_ID}

m4 -DBROKER_ID=$BROKER_ID \
  -DADVERTISED_HOST_NAME=$(hostname -f) \
  -DKAFKA_LOG_DIRS=$KAFKA_LOG_DIRS \
  -DZOOKEEPER_CONNECT=$ZOOKEEPER_CONNECT \
  $SERVER_PROPERTIES_M4_PATH \
  > /etc/service/kafka/server.properties

export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:${LOG4J_PROPERTIES_PATH}"
chown -R kafka:kafka $KAFKA_LOG_DIRS

trap stop_kafka EXIT
start_kafka
