apiVersion: v1
kind: Secret
metadata:
  name: kafka
type: Opaque
data:
  log4j.properties: bG9nNGoucm9vdExvZ2dlcj1XQVJOLCBjb25zb2xlLCBzeXNsb2cKCiMgQ29uc29sZSBhcHBlbmRlcgpsb2c0ai5hcHBlbmRlci5jb25zb2xlPW9yZy5hcGFjaGUubG9nNGouQ29uc29sZUFwcGVuZGVyCmxvZzRqLmFwcGVuZGVyLmNvbnNvbGUubGF5b3V0PW9yZy5hcGFjaGUubG9nNGouUGF0dGVybkxheW91dApsb2c0ai5hcHBlbmRlci5jb25zb2xlLmxheW91dC5Db252ZXJzaW9uUGF0dGVybj0lLTVwICVjOiAlbSVuCgojIFN5c2xvZyBhcHBlbmRlcgpsb2c0ai5hcHBlbmRlci5zeXNsb2c9b3JnLmFwYWNoZS5sb2c0ai5uZXQuU3lzbG9nQXBwZW5kZXIKbG9nNGouYXBwZW5kZXIuc3lzbG9nLlN5c2xvZ0hvc3Q9bG9jYWxob3N0CmxvZzRqLmFwcGVuZGVyLnN5c2xvZy5GYWNpbGl0eT1Mb2NhbDMKbG9nNGouYXBwZW5kZXIuc3lzbG9nLkhlYWRlcj10cnVlCmxvZzRqLmFwcGVuZGVyLnN5c2xvZy5sYXlvdXQ9b3JnLmFwYWNoZS5sb2c0ai5FbmhhbmNlZFBhdHRlcm5MYXlvdXQKbG9nNGouYXBwZW5kZXIuc3lzbG9nLmxheW91dC5Db252ZXJzaW9uUGF0dGVybj1rYWZrYSAlZHtJU084NjAxfXtVVEN9ICVwICV0ICVjezF9LiVNIC0gJW0lbgo=
