kind: Service
apiVersion: v1
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      protocol: TCP
      name: kafka-broker
  selector:
    role: kafka
  type: ClusterIP
